# Topic ideas

---

Group name: Antonino Piloro

---

## Name of topic idea 1
## Fussball-Daten Analyse
Im vorherigen Modul habe ich bereits mit diesen Daten gearbeitet. Darauf bauend könnte ich diese mit statistische Methoden analysieren.

### Data source

Die Daten kommt aus transfermarkt.de. Der Datensatz wurde von einem Kaggle User über ein nicht offiziellen transfermarkt [scraper](https://github.com/dcaribou/transfermarkt-scraper) gesammelt. Darüber hinaus wurde der Vorgang automatisiert und eine Pipeline aufgebaut, somit jede Woche neue Daten gescraped werden. Somit stellt der Ersteller eine immer aktuelle Datenverfügbarkeit dar. Hier der [Link](https://github.com/dcaribou/transfermarkt-datasets?tab=readme-ov-file) zum Github der Datensätze und der [Link](https://www.kaggle.com/datasets/davidcariboo/player-scores/data) zum dazugehörigen Kaggle.




### Data characterisitcs

Die Daten aus Kaggle beinhalten alle wichtigen Informationen aus der Fussball Welt. Der Datensatz besteht aus mehreren CSV-Dateien mit Informationen zu Wettbewerben, Spielen, Vereinen, Spielern und Auftritten. Jede Datei enthält die Attribute der Entität und die IDs, die verwendet werden können, um sie miteinander zu joinen. 
Alle Datensätze gejoined entstehen hier mehr als 10 Spalten und 100 Reihen.

Allgemein kann man in den Daten Infos aus jedes einzelnes Spiel (Tore, gelbe/rote Karten, Schiedsrichter), Aufstellungen zu jedem verfügbaren Spiel (Startelf, Auswechsel), Wettbewerbe (welche es gibt), Bewertung eines Spieles auf Spieler Ebene (Tore, gelbe/rote Karten, Spielzeit), Marktwert der Spieler, genauere Infos zu einem Spielverlauf (wenn ein Spieler eine Karte bekam, dann wird beschrieben wieso und wann; genauso bei einem Tor eine genaurer Beschreibung vorliegt), alle Infos zu den einezelnen transfers (Gebühren, derzeitiger Marktwert, woher zu wohin), ausgiebige Infos zu jeden einzelnen Spieler (Größe, Alter, Position, Geburtsort, Füßigkeit, uvm) und allgemeine Infos auf Verein Ebene (erzielte Tore, erhaltene Gegentore, Ausländerrate, Mannschaftsgröße, Stadiumsgröße, Netto Transfer Bilanz). 





### Research question

Anhand all dieser Daten kann man wahrscheinlich viele Analysen machen.
Ideen für Response-Variablen:

**Marktwert eines Spielers**
- Welche Faktoren beeinflussen den Marktwert am meisten? Sind dies Leistung, Position, Alter oder Transferhistorie? Oder haben bestimmte Wettbewerbe und Liga-Ebene einen stärkeren Einfluss?

**Einfluss auf die Teamleistung**
- Sollte der Fokus auf der individuellen Leistung liegen oder auf dem Beitrag zum Team?
-Der Einfluss eines Spielers auf das Gesamtergebnis und den Erfolg seines Teams (Siegquote, erreichte Tore und Gegentore, Teamplatzierung, Spielzeit pro Saison)

**Spielerdemografie**
- Alter, Nationalität, Größe, bevorzugter Fuß und Position auf dem Spielfeld
- Wie stark beeinflussen demografische Merkmale wie das Alter oder die Position den Marktwert eines Spielers? Gibt es bestimmte Kombinationen, wie z.B. junge, groß gewachsene Stürmer, die einen höheren Marktwert erzielen? Inwieweit sind diese demografischen Merkmale auch in verschiedenen Ligen unterschiedlich wertvoll?


Mir ist aber noch nicht ganz klar welchen Weg ich einschlagen werde.

In [1]:
import pandas as pd
import os

In [10]:
### Overview of data

match_aufstellung_df = pd.read_csv(f"{new_path}/game_lineups.csv")
wettbewerb_df = pd.read_csv(f"{new_path}/competitions.csv")
appearances_df = pd.read_csv(f"{new_path}/appearances.csv")
spieler_wert_df = pd.read_csv(f"{new_path}/player_valuations.csv")
spiel_events_df = pd.read_csv(f"{new_path}/game_events.csv")
transfers_df = pd.read_csv(f"{new_path}/transfers.csv")
spieler_df = pd.read_csv(f"{new_path}/players.csv")
matches_df = pd.read_csv(f"{new_path}/games.csv")
verein_matches_df = pd.read_csv(f"{new_path}/club_games.csv")
vereine_df = pd.read_csv(f"{new_path}/clubs.csv")

In [12]:
match_aufstellung_df.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url,is_major_national_league
0,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,False
1,NLSC,johan-cruijff-schaal,johan-cruijff-schaal,domestic_super_cup,other,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/johan-cruijff-...,False
2,GRP,kypello-elladas,kypello-elladas,domestic_cup,domestic_cup,56,Greece,GR1,europa,https://www.transfermarkt.co.uk/kypello-ellada...,False
3,POSU,supertaca-candido-de-oliveira,supertaca-candido-de-oliveira,domestic_super_cup,other,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/supertaca-cand...,False
4,RUSS,russian-super-cup,russian-super-cup,domestic_super_cup,other,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-super-...,False

In [13]:
wettbewerb_df.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url,is_major_national_league
0,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,False
1,NLSC,johan-cruijff-schaal,johan-cruijff-schaal,domestic_super_cup,other,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/johan-cruijff-...,False
2,GRP,kypello-elladas,kypello-elladas,domestic_cup,domestic_cup,56,Greece,GR1,europa,https://www.transfermarkt.co.uk/kypello-ellada...,False
3,POSU,supertaca-candido-de-oliveira,supertaca-candido-de-oliveira,domestic_super_cup,other,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/supertaca-cand...,False
4,RUSS,russian-super-cup,russian-super-cup,domestic_super_cup,other,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-super-...,False

In [14]:
appearances_df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [15]:
spieler_wert_df.head()

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,3057,BE1
1,342216,2001-07-20,100000,1241,SC1
2,3132,2003-12-09,400000,126,TR1
3,6893,2003-12-15,900000,984,GB1
4,10,2004-10-04,7000000,398,IT1

In [16]:
spiel_events_df.head()

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,", Not reported",49499.0,NaN

In [17]:
transfers_df.head()

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,195778,2026-06-30,25/26,79,27,VfB Stuttgart,Bayern Munich,0.0,12000000.0,Alexander Nübel
1,569033,2026-06-30,25/26,39,27,1.FSV Mainz 05,Bayern Munich,0.0,4000000.0,Armindo Sieb
2,626913,2026-06-30,25/26,398,380,Lazio,Salernitana,0.0,15000000.0,Boulaye Dia
3,1047109,2026-06-30,25/26,2672,265,APO Levadiakos,Panathinaikos,0.0,100000.0,Georgios Katris
4,360791,2025-12-31,25/26,6418,1030,Panetolikos,Argentinos Jrs.,0.0,1200000.0,Lucas Chaves

In [18]:
spieler_df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [19]:
matches_df.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2321044,L1,2013,2. Matchday,2013-08-18,16,23,2,1,1.0,...,SIGNAL IDUNA PARK,80200.0,Peter Sippel,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,4-3-2-1,Borussia Dortmund,Eintracht Braunschweig,2:1,domestic_league
1,2321060,L1,2013,3. Matchday,2013-08-25,23,24,0,2,18.0,...,EINTRACHT-Stadion,23325.0,Wolfgang Stark,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-2-3-1,Eintracht Braunschweig,Eintracht Frankfurt Fußball AG,0:2,domestic_league
2,2321086,L1,2013,6. Matchday,2013-09-21,4,16,1,1,15.0,...,Max-Morlock-Stadion,50000.0,Knut Kircher,https://www.transfermarkt.co.uk/1-fc-nuremberg...,4-2-3-1,4-2-3-1,1.FC Nuremberg,Borussia Dortmund,1:1,domestic_league
3,2321152,L1,2013,11. Matchday,2013-11-02,44,33,0,2,7.0,...,Olympiastadion Berlin,69277.0,Günter Perl,https://www.transfermarkt.co.uk/hertha-bsc_fc-...,4-2-3-1,4-2-3-1,Hertha BSC,FC Schalke 04,0:2,domestic_league
4,2321205,L1,2013,17. Matchday,2013-12-21,41,39,2,3,14.0,...,Volksparkstadion,50000.0,Bastian Dankert,https://www.transfermarkt.co.uk/hamburger-sv_1...,4-2-3-1,4-4-2 Diamond,Hamburger SV,1. Fußball- und Sportverein Mainz 05,2:3,domestic_league

In [20]:
verein_matches_df.head()

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,2320450,1468,0,NaN,Holger Bachthaler,24,2,NaN,Armin Veh,Home,0
1,2320460,1,3,NaN,Jürgen Luginger,86,1,NaN,Robin Dutt,Home,1
2,2320472,2036,4,NaN,Frank Schmidt,72,5,NaN,Alexander Schmidt,Home,0
3,2321044,16,2,1.0,Jürgen Klopp,23,1,15.0,Torsten Lieberknecht,Home,1
4,2321060,23,0,18.0,Torsten Lieberknecht,24,2,11.0,Armin Veh,Home,0

In [21]:
vereine_df.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,SV Darmstadt 98,L1,NaN,27,25.6,13,48.1,1,Merck-Stadion am Böllenfalltor,17810,+€3.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,Ural Yekaterinburg,RU1,NaN,30,26.5,11,36.7,3,Yekaterinburg Arena,23000,+€880k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,31,26.2,16,51.6,7,Tüpraş Stadyumu,42445,€-18.65m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,26.3,19,73.1,19,Olimpico di Roma,73261,€-65.60m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,26,25.5,18,69.2,17,Tottenham Hotspur Stadium,62850,€-93.55m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...

## Name of topic idea 2
Die zweite Idee wär an meinem Churnmodell, welches ich bei der Bank betreue, zu arbeiten. Jedoch würde ich die Daten dazu neimals bekommen können, da diese sehr sensibel sind und ich mein Projekt auf meinem privaten Mac machen möchte/muss. Nach zu generieren wäre wahrscheinlich möglich aber sehr aufwendig da wir im Bertrieb ein Dataframe mit fast 1000 Spalten auf Basis einer 12 Monatige Pivotierung.



### Data source

*State the source of the data set and describe when and how it was originally collected (by the original data curator, not necessarily how you found the data)*


### Data characterisitcs

 *Describe the observations and the general characteristics being measured in the data (note that the data needs to meet the  criteria described in the project description)*

### Research question

*Describe a research question you're interested in answering using this data. State the response variable and possible predictor variables.*

### Overview of data

*Use the Pandas functions to provide an overview of the data set*